// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommonModelMessages_External.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from CommonModelMessages_External.proto</summary>
public static partial class CommonModelMessagesExternalReflection {

  #region Descriptor
  /// <summary>File descriptor for CommonModelMessages_External.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommonModelMessagesExternalReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiJDb21tb25Nb2RlbE1lc3NhZ2VzX0V4dGVybmFsLnByb3RvIikKDVByb3Rv",
          "SW50UmFuZ2USDAoEZnJvbRgBIAEoBRIKCgJ0bxgCIAEoBSIqCg5Qcm90b0xv",
          "bmdSYW5nZRIMCgRmcm9tGAEgASgDEgoKAnRvGAIgASgDIiwKEFByb3RvRG91",
          "YmxlUmFuZ2USDAoEZnJvbRgBIAEoARIKCgJ0bxgCIAEoASI4CgxQcm90b0dl",
          "b0luZm8SFgoOY291bnRyeUlzb0NvZGUYASABKAkSEAoIY2l0eU5hbWUYAiAB",
          "KAkqtQQKEFByb3RvUGF5bG9hZFR5cGUSEQoNUFJPVE9fTUVTU0FHRRAFEiMK",
          "H1BST1RPX1NFUlZFUl9ERVBUSF9RVU9URVNfRVZFTlQQAhIbChdQUk9UT19T",
          "RVJWRVJfU1BPVF9FVkVOVBADEhwKGFBST1RPX1NFUlZFUl9ERVBUSF9FVkVO",
          "VBAEEioKJlBST1RPX1NFUlZFUl9UUkFJTElOR19TTF9DSEFOR0VEX0VWRU5U",
          "EAYSIgoeUFJPVE9fU0VSVkVSX01BUktFVF9EQVRBX0VWRU5UEAcSDQoJRVJS",
          "T1JfUkVTEDISEwoPSEVBUlRCRUFUX0VWRU5UEDMSDAoIUElOR19SRVEQNBIM",
          "CghQSU5HX1JFUxA1EiMKH1JFR0lTVEVSX0NTRVJWRVJfQ09OTkVDVElPTl9S",
          "RVEQNhIjCh9SRUdJU1RFUl9DU0VSVkVSX0NPTk5FQ1RJT05fUkVTEDcSJQoh",
          "VU5SRUdJU1RFUl9DU0VSVkVSX0NPTk5FQ1RJT05fUkVREDgSJQohVU5SRUdJ",
          "U1RFUl9DU0VSVkVSX0NPTk5FQ1RJT05fUkVTEDkSHwobUkVHSVNURVJfQ0lE",
          "X0NPTk5FQ1RJT05fUkVREDoSHwobUkVHSVNURVJfQ0lEX0NPTk5FQ1RJT05f",
          "UkVTEDsSIQodVU5SRUdJU1RFUl9DSURfQ09OTkVDVElPTl9SRVEQPBIhCh1V",
          "TlJFR0lTVEVSX0NJRF9DT05ORUNUSU9OX1JFUxA9KqQCCg5Qcm90b0Vycm9y",
          "Q29kZRIRCg1VTktOT1dOX0VSUk9SEAESFwoTVU5TVVBQT1JURURfTUVTU0FH",
          "RRACEhMKD0lOVkFMSURfUkVRVUVTVBADEhIKDldST05HX1BBU1NXT1JEEAQS",
          "EQoNVElNRU9VVF9FUlJPUhAFEhQKEEVOVElUWV9OT1RfRk9VTkQQBhIWChJD",
          "QU5UX1JPVVRFX1JFUVVFU1QQBxISCg5GUkFNRV9UT09fTE9ORxAIEhEKDU1B",
          "UktFVF9DTE9TRUQQCRIbChdDT05DVVJSRU5UX01PRElGSUNBVElPThAKEhgK",
          "FEJMT0NLRURfUEFZTE9BRF9UWVBFEAsSHgoaREFUQVNUT1JFX0lTX05PVF9B",
          "VkFJTEFCTEUQDEJNCihjb20ueHRyYWRlci5wcm90b2NvbC5wcm90by5jb21t",
          "b25zLm1vZGVsQhxDb250YWluZXJDb21tb25Nb2RlbE1lc3NhZ2VzUAGgAQE="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoPayloadType), typeof(global::ProtoErrorCode), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoIntRange), global::ProtoIntRange.Parser, new[]{ "From", "To" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoLongRange), global::ProtoLongRange.Parser, new[]{ "From", "To" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoDoubleRange), global::ProtoDoubleRange.Parser, new[]{ "From", "To" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoGeoInfo), global::ProtoGeoInfo.Parser, new[]{ "CountryIsoCode", "CityName" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// Enum for payload type
/// </summary>
public enum ProtoPayloadType {
  [pbr::OriginalName("PROTO_MESSAGE")] ProtoMessage = 5,
  [pbr::OriginalName("PROTO_SERVER_DEPTH_QUOTES_EVENT")] ProtoServerDepthQuotesEvent = 2,
  [pbr::OriginalName("PROTO_SERVER_SPOT_EVENT")] ProtoServerSpotEvent = 3,
  [pbr::OriginalName("PROTO_SERVER_DEPTH_EVENT")] ProtoServerDepthEvent = 4,
  [pbr::OriginalName("PROTO_SERVER_TRAILING_SL_CHANGED_EVENT")] ProtoServerTrailingSlChangedEvent = 6,
  [pbr::OriginalName("PROTO_SERVER_MARKET_DATA_EVENT")] ProtoServerMarketDataEvent = 7,
  [pbr::OriginalName("ERROR_RES")] ErrorRes = 50,
  [pbr::OriginalName("HEARTBEAT_EVENT")] HeartbeatEvent = 51,
  [pbr::OriginalName("PING_REQ")] PingReq = 52,
  [pbr::OriginalName("PING_RES")] PingRes = 53,
  [pbr::OriginalName("REGISTER_CSERVER_CONNECTION_REQ")] RegisterCserverConnectionReq = 54,
  [pbr::OriginalName("REGISTER_CSERVER_CONNECTION_RES")] RegisterCserverConnectionRes = 55,
  [pbr::OriginalName("UNREGISTER_CSERVER_CONNECTION_REQ")] UnregisterCserverConnectionReq = 56,
  [pbr::OriginalName("UNREGISTER_CSERVER_CONNECTION_RES")] UnregisterCserverConnectionRes = 57,
  [pbr::OriginalName("REGISTER_CID_CONNECTION_REQ")] RegisterCidConnectionReq = 58,
  [pbr::OriginalName("REGISTER_CID_CONNECTION_RES")] RegisterCidConnectionRes = 59,
  [pbr::OriginalName("UNREGISTER_CID_CONNECTION_REQ")] UnregisterCidConnectionReq = 60,
  [pbr::OriginalName("UNREGISTER_CID_CONNECTION_RES")] UnregisterCidConnectionRes = 61,
}

/// <summary>
/// Enum for error code
/// </summary>
public enum ProtoErrorCode {
  [pbr::OriginalName("UNKNOWN_ERROR")] UnknownError = 1,
  [pbr::OriginalName("UNSUPPORTED_MESSAGE")] UnsupportedMessage = 2,
  [pbr::OriginalName("INVALID_REQUEST")] InvalidRequest = 3,
  [pbr::OriginalName("WRONG_PASSWORD")] WrongPassword = 4,
  [pbr::OriginalName("TIMEOUT_ERROR")] TimeoutError = 5,
  [pbr::OriginalName("ENTITY_NOT_FOUND")] EntityNotFound = 6,
  [pbr::OriginalName("CANT_ROUTE_REQUEST")] CantRouteRequest = 7,
  [pbr::OriginalName("FRAME_TOO_LONG")] FrameTooLong = 8,
  [pbr::OriginalName("MARKET_CLOSED")] MarketClosed = 9,
  [pbr::OriginalName("CONCURRENT_MODIFICATION")] ConcurrentModification = 10,
  [pbr::OriginalName("BLOCKED_PAYLOAD_TYPE")] BlockedPayloadType = 11,
  [pbr::OriginalName("DATASTORE_IS_NOT_AVAILABLE")] DatastoreIsNotAvailable = 12,
}

#endregion

#region Messages
/// <summary>
/// Type for range
/// </summary>
public sealed partial class ProtoIntRange : pb::IMessage<ProtoIntRange>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoIntRange> _parser = new pb::MessageParser<ProtoIntRange>(() => new ProtoIntRange());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoIntRange> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonModelMessagesExternalReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoIntRange() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoIntRange(ProtoIntRange other) : this() {
    _hasBits0 = other._hasBits0;
    from_ = other.from_;
    to_ = other.to_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoIntRange Clone() {
    return new ProtoIntRange(this);
  }

  /// <summary>Field number for the "from" field.</summary>
  public const int FromFieldNumber = 1;
  private readonly static int FromDefaultValue = 0;

  private int from_;
  /// <summary>
  /// Start of the range
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int From {
    get { if ((_hasBits0 & 1) != 0) { return from_; } else { return FromDefaultValue; } }
    set {
      _hasBits0 |= 1;
      from_ = value;
    }
  }
  /// <summary>Gets whether the "from" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFrom {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "from" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFrom() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "to" field.</summary>
  public const int ToFieldNumber = 2;
  private readonly static int ToDefaultValue = 0;

  private int to_;
  /// <summary>
  /// End of the range
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int To {
    get { if ((_hasBits0 & 2) != 0) { return to_; } else { return ToDefaultValue; } }
    set {
      _hasBits0 |= 2;
      to_ = value;
    }
  }
  /// <summary>Gets whether the "to" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTo {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "to" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTo() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoIntRange);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoIntRange other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (From != other.From) return false;
    if (To != other.To) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasFrom) hash ^= From.GetHashCode();
    if (HasTo) hash ^= To.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasFrom) {
      output.WriteRawTag(8);
      output.WriteInt32(From);
    }
    if (HasTo) {
      output.WriteRawTag(16);
      output.WriteInt32(To);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasFrom) {
      output.WriteRawTag(8);
      output.WriteInt32(From);
    }
    if (HasTo) {
      output.WriteRawTag(16);
      output.WriteInt32(To);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasFrom) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(From);
    }
    if (HasTo) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(To);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoIntRange other) {
    if (other == null) {
      return;
    }
    if (other.HasFrom) {
      From = other.From;
    }
    if (other.HasTo) {
      To = other.To;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          From = input.ReadInt32();
          break;
        }
        case 16: {
          To = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          From = input.ReadInt32();
          break;
        }
        case 16: {
          To = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Type for range (long)
/// </summary>
public sealed partial class ProtoLongRange : pb::IMessage<ProtoLongRange>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoLongRange> _parser = new pb::MessageParser<ProtoLongRange>(() => new ProtoLongRange());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoLongRange> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonModelMessagesExternalReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoLongRange() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoLongRange(ProtoLongRange other) : this() {
    _hasBits0 = other._hasBits0;
    from_ = other.from_;
    to_ = other.to_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoLongRange Clone() {
    return new ProtoLongRange(this);
  }

  /// <summary>Field number for the "from" field.</summary>
  public const int FromFieldNumber = 1;
  private readonly static long FromDefaultValue = 0L;

  private long from_;
  /// <summary>
  /// Start of the range
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long From {
    get { if ((_hasBits0 & 1) != 0) { return from_; } else { return FromDefaultValue; } }
    set {
      _hasBits0 |= 1;
      from_ = value;
    }
  }
  /// <summary>Gets whether the "from" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFrom {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "from" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFrom() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "to" field.</summary>
  public const int ToFieldNumber = 2;
  private readonly static long ToDefaultValue = 0L;

  private long to_;
  /// <summary>
  /// End of the range
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long To {
    get { if ((_hasBits0 & 2) != 0) { return to_; } else { return ToDefaultValue; } }
    set {
      _hasBits0 |= 2;
      to_ = value;
    }
  }
  /// <summary>Gets whether the "to" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTo {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "to" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTo() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoLongRange);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoLongRange other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (From != other.From) return false;
    if (To != other.To) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasFrom) hash ^= From.GetHashCode();
    if (HasTo) hash ^= To.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasFrom) {
      output.WriteRawTag(8);
      output.WriteInt64(From);
    }
    if (HasTo) {
      output.WriteRawTag(16);
      output.WriteInt64(To);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasFrom) {
      output.WriteRawTag(8);
      output.WriteInt64(From);
    }
    if (HasTo) {
      output.WriteRawTag(16);
      output.WriteInt64(To);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasFrom) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(From);
    }
    if (HasTo) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(To);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoLongRange other) {
    if (other == null) {
      return;
    }
    if (other.HasFrom) {
      From = other.From;
    }
    if (other.HasTo) {
      To = other.To;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          From = input.ReadInt64();
          break;
        }
        case 16: {
          To = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          From = input.ReadInt64();
          break;
        }
        case 16: {
          To = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Type for double range
/// </summary>
public sealed partial class ProtoDoubleRange : pb::IMessage<ProtoDoubleRange>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoDoubleRange> _parser = new pb::MessageParser<ProtoDoubleRange>(() => new ProtoDoubleRange());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoDoubleRange> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonModelMessagesExternalReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoDoubleRange() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoDoubleRange(ProtoDoubleRange other) : this() {
    _hasBits0 = other._hasBits0;
    from_ = other.from_;
    to_ = other.to_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoDoubleRange Clone() {
    return new ProtoDoubleRange(this);
  }

  /// <summary>Field number for the "from" field.</summary>
  public const int FromFieldNumber = 1;
  private readonly static double FromDefaultValue = 0D;

  private double from_;
  /// <summary>
  /// Start of the range
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double From {
    get { if ((_hasBits0 & 1) != 0) { return from_; } else { return FromDefaultValue; } }
    set {
      _hasBits0 |= 1;
      from_ = value;
    }
  }
  /// <summary>Gets whether the "from" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFrom {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "from" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFrom() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "to" field.</summary>
  public const int ToFieldNumber = 2;
  private readonly static double ToDefaultValue = 0D;

  private double to_;
  /// <summary>
  /// End of the range
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double To {
    get { if ((_hasBits0 & 2) != 0) { return to_; } else { return ToDefaultValue; } }
    set {
      _hasBits0 |= 2;
      to_ = value;
    }
  }
  /// <summary>Gets whether the "to" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTo {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "to" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTo() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoDoubleRange);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoDoubleRange other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(From, other.From)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(To, other.To)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasFrom) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(From);
    if (HasTo) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(To);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasFrom) {
      output.WriteRawTag(9);
      output.WriteDouble(From);
    }
    if (HasTo) {
      output.WriteRawTag(17);
      output.WriteDouble(To);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasFrom) {
      output.WriteRawTag(9);
      output.WriteDouble(From);
    }
    if (HasTo) {
      output.WriteRawTag(17);
      output.WriteDouble(To);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasFrom) {
      size += 1 + 8;
    }
    if (HasTo) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoDoubleRange other) {
    if (other == null) {
      return;
    }
    if (other.HasFrom) {
      From = other.From;
    }
    if (other.HasTo) {
      To = other.To;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          From = input.ReadDouble();
          break;
        }
        case 17: {
          To = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          From = input.ReadDouble();
          break;
        }
        case 17: {
          To = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Type for geo info
/// </summary>
public sealed partial class ProtoGeoInfo : pb::IMessage<ProtoGeoInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoGeoInfo> _parser = new pb::MessageParser<ProtoGeoInfo>(() => new ProtoGeoInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoGeoInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonModelMessagesExternalReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoGeoInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoGeoInfo(ProtoGeoInfo other) : this() {
    countryIsoCode_ = other.countryIsoCode_;
    cityName_ = other.cityName_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoGeoInfo Clone() {
    return new ProtoGeoInfo(this);
  }

  /// <summary>Field number for the "countryIsoCode" field.</summary>
  public const int CountryIsoCodeFieldNumber = 1;
  private readonly static string CountryIsoCodeDefaultValue = "";

  private string countryIsoCode_;
  /// <summary>
  /// Country ISO code
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CountryIsoCode {
    get { return countryIsoCode_ ?? CountryIsoCodeDefaultValue; }
    set {
      countryIsoCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "countryIsoCode" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCountryIsoCode {
    get { return countryIsoCode_ != null; }
  }
  /// <summary>Clears the value of the "countryIsoCode" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCountryIsoCode() {
    countryIsoCode_ = null;
  }

  /// <summary>Field number for the "cityName" field.</summary>
  public const int CityNameFieldNumber = 2;
  private readonly static string CityNameDefaultValue = "";

  private string cityName_;
  /// <summary>
  /// City name
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CityName {
    get { return cityName_ ?? CityNameDefaultValue; }
    set {
      cityName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "cityName" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCityName {
    get { return cityName_ != null; }
  }
  /// <summary>Clears the value of the "cityName" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCityName() {
    cityName_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoGeoInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoGeoInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CountryIsoCode != other.CountryIsoCode) return false;
    if (CityName != other.CityName) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasCountryIsoCode) hash ^= CountryIsoCode.GetHashCode();
    if (HasCityName) hash ^= CityName.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasCountryIsoCode) {
      output.WriteRawTag(10);
      output.WriteString(CountryIsoCode);
    }
    if (HasCityName) {
      output.WriteRawTag(18);
      output.WriteString(CityName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasCountryIsoCode) {
      output.WriteRawTag(10);
      output.WriteString(CountryIsoCode);
    }
    if (HasCityName) {
      output.WriteRawTag(18);
      output.WriteString(CityName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasCountryIsoCode) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CountryIsoCode);
    }
    if (HasCityName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CityName);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoGeoInfo other) {
    if (other == null) {
      return;
    }
    if (other.HasCountryIsoCode) {
      CountryIsoCode = other.CountryIsoCode;
    }
    if (other.HasCityName) {
      CityName = other.CityName;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          CountryIsoCode = input.ReadString();
          break;
        }
        case 18: {
          CityName = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          CountryIsoCode = input.ReadString();
          break;
        }
        case 18: {
          CityName = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
